package model;

public enum Specialties {
    VIDEOGAMEDESIGNER,
    QUALITYASSURANCEENGINEER,
    CRMPROJECTMANAGER,
    SOFTWAREINTEGRATIONENGINEER,
    SECURITYENGINEER,
    FRONTENDENGINEER,
    FULLSTACKENGINEER,
    GRAPHICSDEVELOPER,
    DATASCIENTIST,
    MOBILEDEVELOPER,
    BACKENDENGINEER;

}
