namespace BlazorSep3.model
{
    public enum Specialities
    {
        VIDEOGAMEDESIGNER,
        QUALITYASSURANCEENGINEER,
        CRMPROJECTMANAGER,
        SOFTWAREINTEGRATIONENGINEER,
        SECURITYENGINEER,
        FRONTENDENGINEER,
        FULLSTACKENGINEER,
        GRAPHICSDEVELOPER,
        DATASCIENTIST,
        MOBILEDEVELOPER,
        BACKENDENGINEER
    }
}